# Generated by Django 6.0.5 on 2026-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='manager_note',
            field=models.TextField(blank=True),
        ),
    ]
