# Generated by Django 6.0.5 on 2026-06-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_manager_note_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('classified', 'Classified'), ('routed', 'Routed'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('comment_added', 'Comment Added'), ('closed', 'Closed')], default='status_changed', max_length=30),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
