# Generated by Django 6.0.5 on 2026-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_tickethistory_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='new_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20),
        ),
    ]
